// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmLhTFCofeCEt2FyXAAaTSR9SJpj5v1I',
    appId: '1:991307126024:web:1d752c5fddc2023d3a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    authDomain: 'ellemoratest-a7628.firebaseapp.com',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    measurementId: 'G-WR2LZ13FRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDNcx9_BMi73_urvFY7CfYNJo3g9Ps2A',
    appId: '1:991307126024:android:506e458ee403c9433a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    storageBucket: 'ellemoratest-a7628.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmLhTFCofeCEt2FyXAAaTSR9SJpj5v1I',
    appId: '1:991307126024:web:d512bb3e49b4fc6b3a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    authDomain: 'ellemoratest-a7628.firebaseapp.com',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    measurementId: 'G-4FW089K71V',
  );
}
